In [1]:
import pandas as pd

In [2]:
d1=pd.read_csv(r"C:\Users\Yuvaraj S\OneDrive\Desktop\16MLP\claimants.csv")
d1

,CASENUM,ATTORNEY,CLMSEX,CLMINSUR,SEATBELT,CLMAGE,LOSS
0,5,0,0.0,1.0,0.0,50.0,34.940
1,3,1,1.0,0.0,0.0,18.0,0.891
2,66,1,0.0,1.0,0.0,5.0,0.330
3,70,0,0.0,1.0,1.0,31.0,0.037
4,96,1,0.0,1.0,0.0,30.0,0.038
...,...,...,...,...,...,...,...
1335,34100,1,0.0,1.0,0.0,NaN,0.576
1336,34110,0,1.0,1.0,0.0,46.0,3.705
1337,34113,1,1.0,1.0,0.0,39.0,0.099
1338,34145,0,1.0,0.0,0.0,8.0,3.177


In [34]:
del d1['CASENUM']

In [35]:
d1

,ATTORNEY,CLMSEX,CLMINSUR,SEATBELT,CLMAGE,LOSS
0,0,0.0,1.0,0.0,50.0,34.940
1,1,1.0,0.0,0.0,18.0,0.891
2,1,0.0,1.0,0.0,5.0,0.330
3,0,0.0,1.0,1.0,31.0,0.037
4,1,0.0,1.0,0.0,30.0,0.038
...,...,...,...,...,...,...
1091,1,1.0,1.0,0.0,16.0,0.060
1092,0,1.0,1.0,0.0,46.0,3.705
1093,1,1.0,1.0,0.0,39.0,0.099
1094,0,1.0,0.0,0.0,8.0,3.177


In [36]:
d1.shape

(1096, 6)

In [37]:
d1.dtypes

ATTORNEY      int64
CLMSEX      float64
CLMINSUR    float64
SEATBELT    float64
CLMAGE      float64
LOSS        float64
dtype: object

In [38]:
d1.isna().sum()

ATTORNEY    0
CLMSEX      0
CLMINSUR    0
SEATBELT    0
CLMAGE      0
LOSS        0
dtype: int64

In [7]:
d1.dropna(inplace=True,ignore_index=True)

In [39]:
d1

,ATTORNEY,CLMSEX,CLMINSUR,SEATBELT,CLMAGE,LOSS
0,0,0.0,1.0,0.0,50.0,34.940
1,1,1.0,0.0,0.0,18.0,0.891
2,1,0.0,1.0,0.0,5.0,0.330
3,0,0.0,1.0,1.0,31.0,0.037
4,1,0.0,1.0,0.0,30.0,0.038
...,...,...,...,...,...,...
1091,1,1.0,1.0,0.0,16.0,0.060
1092,0,1.0,1.0,0.0,46.0,3.705
1093,1,1.0,1.0,0.0,39.0,0.099
1094,0,1.0,0.0,0.0,8.0,3.177


In [15]:
d1.duplicated().sum()

np.int64(8)

In [16]:
d1[d1.duplicated()]

,ATTORNEY,CLMSEX,CLMINSUR,SEATBELT,CLMAGE,LOSS
363,1,0.0,1.0,0.0,57.0,3.889
683,0,1.0,1.0,0.0,48.0,1.050
706,1,1.0,1.0,0.0,30.0,0.300
765,0,1.0,1.0,0.0,8.0,0.100
786,1,0.0,1.0,0.0,11.0,0.500
804,0,1.0,1.0,0.0,43.0,8.490
878,0,0.0,1.0,0.0,7.0,0.640
1032,1,0.0,1.0,0.0,0.0,0.440


In [40]:
d1.drop_duplicates(inplace=True,ignore_index=True)

In [41]:
d1

,ATTORNEY,CLMSEX,CLMINSUR,SEATBELT,CLMAGE,LOSS
0,0,0.0,1.0,0.0,50.0,34.940
1,1,1.0,0.0,0.0,18.0,0.891
2,1,0.0,1.0,0.0,5.0,0.330
3,0,0.0,1.0,1.0,31.0,0.037
4,1,0.0,1.0,0.0,30.0,0.038
...,...,...,...,...,...,...
1083,1,1.0,1.0,0.0,16.0,0.060
1084,0,1.0,1.0,0.0,46.0,3.705
1085,1,1.0,1.0,0.0,39.0,0.099
1086,0,1.0,0.0,0.0,8.0,3.177


In [42]:
x = d1.iloc[:,1:]
x

,CLMSEX,CLMINSUR,SEATBELT,CLMAGE,LOSS
0,0.0,1.0,0.0,50.0,34.940
1,1.0,0.0,0.0,18.0,0.891
2,0.0,1.0,0.0,5.0,0.330
3,0.0,1.0,1.0,31.0,0.037
4,0.0,1.0,0.0,30.0,0.038
...,...,...,...,...,...
1083,1.0,1.0,0.0,16.0,0.060
1084,1.0,1.0,0.0,46.0,3.705
1085,1.0,1.0,0.0,39.0,0.099
1086,1.0,0.0,0.0,8.0,3.177


In [43]:
y = d1.iloc[:,0]
y

0       0
1       1
2       1
3       0
4       1
       ..
1083    1
1084    0
1085    1
1086    0
1087    1
Name: ATTORNEY, Length: 1088, dtype: int64

In [44]:
d1.corr()

,ATTORNEY,CLMSEX,CLMINSUR,SEATBELT,CLMAGE,LOSS
ATTORNEY,1.000000,0.101974,0.084823,-0.060969,0.001563,-0.226161
CLMSEX,0.101974,1.000000,0.058721,-0.018014,-0.020680,-0.030439
CLMINSUR,0.084823,0.058721,1.000000,0.021553,0.048730,0.019959
SEATBELT,-0.060969,-0.018014,0.021553,1.000000,-0.028605,0.131055
CLMAGE,0.001563,-0.020680,0.048730,-0.028605,1.000000,0.064444
LOSS,-0.226161,-0.030439,0.019959,0.131055,0.064444,1.000000


In [45]:
y.unique()

array([0, 1])

In [46]:
y.value_counts()

ATTORNEY
0    574
1    514
Name: count, dtype: int64

In [47]:
(y.value_counts()[0]/d1.shape[0])*100

np.float64(52.75735294117647)

In [48]:
from sklearn.model_selection import train_test_split

In [49]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=25,shuffle=True)

In [50]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((870, 5), (218, 5), (870,), (218,))

In [51]:
from sklearn.linear_model import LogisticRegression

In [52]:
logr=LogisticRegression()#model bulding
logr.fit(x_train,y_train)#model trainin

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [53]:
y_train_pred = logr.predict(x_train)
y_train_pred

array([0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0,

In [54]:
y_test_pred = logr.predict(x_test)
y_test_pred

array([0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0])

In [55]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [56]:
#train accuracy
confusion_matrix(y_train,y_train_pred)

array([[317, 151],
       [ 97, 305]])

In [57]:
 (317+305)/(317+151+97+305)

0.7149425287356321

In [58]:
accuracy_score(y_train,y_train_pred)

0.7149425287356321

In [59]:
confusion_matrix(y_test,y_test_pred)

array([[74, 32],
       [33, 79]])

In [60]:
print(classification_report(y_train,y_train_pred))

              precision    recall  f1-score   support

           0       0.77      0.68      0.72       468
           1       0.67      0.76      0.71       402

    accuracy                           0.71       870
   macro avg       0.72      0.72      0.71       870
weighted avg       0.72      0.71      0.72       870



In [61]:
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           0       0.69      0.70      0.69       106
           1       0.71      0.71      0.71       112

    accuracy                           0.70       218
   macro avg       0.70      0.70      0.70       218
weighted avg       0.70      0.70      0.70       218

